@startuml

start
:Tutor adds lesson to a tutee;

if () then ([command format is followed])
    if () then ([Lesson does not overlap with the tutor's schedule])
    : Create a ""Lesson"" object;
    :Add the ""Lesson"" to the ""Schedule"";
    :Add the ""Lesson"" to the tutee's lessons;
    :Show command success message;
    else ([else])
    :Show lesson clashes message;
    endif
else ([else])
    :Show command usage message;
endif
stop

@enduml
