@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TrackO *-right-> "1" UniqueTuteeList
TrackO *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueTuteeList
UniqueTagList -[hidden]down- UniqueTuteeList

UniqueTagList *-right-> "*" Tag
UniqueTuteeList -right-> Tutee

Tutee *-up-> "*" Tag

Tutee *--> Name
Tutee *--> Phone
Tutee *--> School
Tutee *--> Level
Tutee *--> Address
Tutee *--> Payment
Tutee *--> Remark
Tutee *-right-> "*" Lesson
@enduml
