@startuml
!include style.puml

box LOGIC_COLOR_T1
participant "CollectivePredicate" as CollectivePredicate LOGIC_COLOR

participant "Stream" as Stream MODEL_COLOR
end box


[-> CollectivePredicate : test(Tutee)
activate CollectivePredicate

CollectivePredicate -> CollectivePredicate : initialiseTests(Tutee)


CollectivePredicate --> CollectivePredicate : activeTests

CollectivePredicate -> Stream : allmatch(bool -> bool)
activate Stream
Stream --> CollectivePredicate
deactivate Stream

[<--CollectivePredicate
deactivate CollectivePredicate
@enduml
