@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTrackO <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class TrackO
Class ReadOnlyTrackO
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniqueTuteeList
Class Tutee
Class Address
Class Email
Class Name
Class Phone
Class Tag

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

TrackO .up.|> ReadOnlyTrackO

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyTrackO
ModelManager -left-> "1" TrackO
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

TrackO *--> "1" UniqueTuteeList
UniqueTuteeList --> "~* all" Tutee
Tutee *--> Name
Tutee *--> Phone
Tutee *--> Email
Tutee *--> Address
Tutee *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"~* filtered" Tutee
@enduml
