@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "payment 1 lesson/1"

package "Payment tracking" <<rectangle>> {

    class Tutee as "__John:Tutee__"
    class Payment as "__p:Payment__" {
         value = "180.00"
         payByDate = null
         paymentHistory = ["Never"]
         isOverdue = false
    }
    class Lesson1 as "__lesson1:Lesson__" {
        subject = "Science"
        time = "Mon 11:00 - 13:00"
        hourlyRate = 90.00
        cost = 180.00
    }
    class Lesson2 as "__lesson2:Lesson__" {
        subject = "Math"
        time = "Tue 12:00 - 13:30"
        hourlyRate = 100.00
        cost = 150.00
    }
}
Tutee -right-> Payment
Tutee -left-> Lesson1
Tutee -down-> Lesson2

show Payment members
show Lesson1 members
show Lesson2 members
hide methods
@end
