@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TrackOParser" as TrackOParser LOGIC_COLOR
participant ":PaymentCommandParser" as PaymentCommandParser LOGIC_COLOR
participant "p:PaymentCommand" as PaymentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("payment 1 add/1 l/1")
activate LogicManager

LogicManager -> TrackOParser : parseCommand("payment 1 add/1 l/1")
activate TrackOParser

create PaymentCommandParser
TrackOParser -> PaymentCommandParser
activate PaymentCommandParser

PaymentCommandParser --> TrackOParser
deactivate PaymentCommandParser

TrackOParser -> PaymentCommandParser : parse("1 add/1 l/1")
activate PaymentCommandParser

create PaymentCommand
PaymentCommandParser -> PaymentCommand
activate PaymentCommand

PaymentCommand --> PaymentCommandParser : p
deactivate PaymentCommand

PaymentCommandParser --> TrackOParser : p
deactivate PaymentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
PaymentCommandParser -[hidden]-> TrackOParser
destroy PaymentCommandParser

TrackOParser --> LogicManager : p
deactivate TrackOParser

LogicManager -> PaymentCommand : execute()
activate PaymentCommand

PaymentCommand -> Model : setTutee(editedTutee)
activate Model

Model --> PaymentCommand
deactivate Model

create CommandResult
PaymentCommand -> CommandResult
activate CommandResult

CommandResult --> PaymentCommand
deactivate CommandResult

PaymentCommand --> LogicManager : result
deactivate PaymentCommand

[<--LogicManager
deactivate LogicManager
@enduml
