@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "add n/John"

package "Payment tracking" <<rectangle>> {

    class Tutee as "__John:Tutee__"
    class Payment as "__p:Payment__" {
         value = "0"
         payByDate = "-"
         paymentHistory = ["Never"]
         isOverdue = false
         addPayment(Lesson, int)
         editPayment(float)
         receivePayment()
         setPayByDate(LocalDate)
    }
}
Tutee -right-> Payment : > owes


show Payment members
@end
