@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor SCHEDULE_COLOR
skinparam classBackgroundColor SCHEDULE_COLOR

package Model{

Class Lesson
Class Tutee
Class Schedule
Class ModelManager

ModelManager -l-> Schedule
Schedule -d-> Lesson
Schedule ..> Tutee
Tutee -r-> Lesson : attends >
ModelManager --> Tutee : tutee list

}

@enduml
