@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "TrackO Storage" #F4F6F6{
Interface TrackOStorage <<Interface>>
Class JsonTrackOStorage
Class JsonSerializableTrackO
Class JsonAdaptedTutee
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" TrackOStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> TrackOStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonTrackOStorage .up.|> TrackOStorage
JsonTrackOStorage ..> JsonSerializableTrackO
JsonSerializableTrackO --> "*" JsonAdaptedTutee
JsonAdaptedTutee --> "*" JsonAdaptedTag

@enduml
